# Generated by Django 5.0.8 on 2024-08-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['surname'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profilesss'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='UserProfiles',
        ),
    ]
