# Generated by Django 5.0.8 on 2024-08-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_players_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='img_link',
            field=models.URLField(null=True),
        ),
    ]
