# Generated by Django 5.0.8 on 2024-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_players_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
