# Generated by Django 5.0.8 on 2024-08-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_players_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='flag_img_link',
            field=models.URLField(null=True),
        ),
    ]
