# Generated by Django 5.0.8 on 2024-08-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_players_flag_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='Best_position',
            field=models.CharField(choices=[('ST', 'St'), ('RB', 'Rb'), ('RW', 'Rw'), ('CDM', 'Cdm')], max_length=50, null=True),
        ),
    ]
