# Generated by Django 5.0.8 on 2024-08-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_players_best_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
